"""Changed strava id to bigint to match API data

Revision ID: 16ab305ab703
Revises: cf237c393912
Create Date: 2022-02-17 12:30:20.879216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ab305ab703'
down_revision = 'cf237c393912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('da', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
