"""Clear up

Revision ID: 2ba750ac4dc1
Revises: d960f65af146
Create Date: 2021-07-24 21:02:53.147798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba750ac4dc1'
down_revision = 'd960f65af146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
