"""Changed strava id to bigint to match API data

Revision ID: 448c1e6a79a5
Revises: 7f7e81cab0a5
Create Date: 2022-02-17 12:37:02.189597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448c1e6a79a5'
down_revision = '7f7e81cab0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strava_activity_id', table_name='strava_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_strava_activity_id', 'strava_activity', ['id'], unique=False)
    # ### end Alembic commands ###
