"""Changed strava id to bigint to match API data

Revision ID: 7f7e81cab0a5
Revises: 16ab305ab703
Create Date: 2022-02-17 12:32:12.182730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7e81cab0a5'
down_revision = '16ab305ab703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
