"""Added Vitamin Classes

Revision ID: 8bd436444d84
Revises: b660485f6f7c
Create Date: 2021-07-19 16:17:30.271484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd436444d84'
down_revision = 'b660485f6f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vitamins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitamins_id'), 'vitamins', ['id'], unique=False)
    op.create_index(op.f('ix_vitamins_name'), 'vitamins', ['name'], unique=True)
    op.create_table('vitamin_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('vitamin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitamin_goals_id'), 'vitamin_goals', ['id'], unique=False)
    op.create_table('vitamin_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('vitamin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitamin_records_id'), 'vitamin_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitamin_records_id'), table_name='vitamin_records')
    op.drop_table('vitamin_records')
    op.drop_index(op.f('ix_vitamin_goals_id'), table_name='vitamin_goals')
    op.drop_table('vitamin_goals')
    op.drop_index(op.f('ix_vitamins_name'), table_name='vitamins')
    op.drop_index(op.f('ix_vitamins_id'), table_name='vitamins')
    op.drop_table('vitamins')
    # ### end Alembic commands ###
