"""Initial Revision

Revision ID: b660485f6f7c
Revises: 
Create Date: 2021-07-19 15:41:40.727289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b660485f6f7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_id'), 'water', ['id'], unique=False)
    op.create_table('water_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_goals_id'), 'water_goals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_goals_id'), table_name='water_goals')
    op.drop_table('water_goals')
    op.drop_index(op.f('ix_water_id'), table_name='water')
    op.drop_table('water')
    # ### end Alembic commands ###
