"""Added Task Classes

Revision ID: b7a85d969960
Revises: 8bd436444d84
Create Date: 2021-07-19 17:22:10.353548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a85d969960'
down_revision = '8bd436444d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('persist', sa.Boolean(), nullable=False),
    sa.Column('freq', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_desc'), 'tasks', ['desc'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('task_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_records_date'), 'task_records', ['date'], unique=False)
    op.create_index(op.f('ix_task_records_id'), 'task_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_records_id'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_date'), table_name='task_records')
    op.drop_table('task_records')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_desc'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
